# Generated by Django 6.0.7 on 2026-07-27 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contract_id', models.CharField(help_text='OCDS or Government Ref ID', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('contractor', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('lga', models.CharField(db_index=True, max_length=100, verbose_name='LGA')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing Work'), ('completed', 'Completed'), ('abandoned', 'Abandoned / Stalled'), ('planned', 'Planned')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CivicFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('ghost', 'Ghost Project (No work on ground)'), ('delay', 'Unexplained Delay / Inactive Site'), ('quality', 'Substandard Materials / Poor Quality'), ('misappropriation', 'Suspected Misappropriation'), ('other', 'Other Issue')], max_length=50)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='civic_flags/evidence/')),
                ('user_latitude', models.FloatField(blank=True, null=True)),
                ('user_longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Investigation'), ('verified', 'Verified Flag'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='flags.procurementproject')),
            ],
        ),
    ]
