# Generated by Django 6.0.7 on 2026-07-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementproject',
            name='state',
            field=models.CharField(db_index=True, default='Lagos', max_length=100),
        ),
    ]
