# Generated by Django 6.0.7 on 2026-07-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_alter_procurementproject_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementproject',
            name='procuring_entity',
            field=models.CharField(blank=True, help_text='Ministry, Department, or Agency (e.g., Ministry of Works)', max_length=255, null=True),
        ),
    ]
