# Generated by Django 6.0.7 on 2026-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0004_civicflag_ip_address_civicflag_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicflag',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
