# Generated by Django 6.0.7 on 2026-07-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentnewsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
