# Generated by Django 6.0.7 on 2026-07-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_governmentnewsarticle_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentnewsarticle',
            options={},
        ),
        migrations.AddField(
            model_name='governmentnewsarticle',
            name='category',
            field=models.CharField(choices=[('gov', 'Governance & Policy'), ('economy', 'Economy & Business'), ('tech', 'Tech & Innovation'), ('society', 'Society & Education'), ('general', 'General News')], db_index=True, default='gov', max_length=20),
        ),
    ]
