# Generated by Django 6.0.7 on 2026-07-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractingRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('release_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('initiation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_name', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('budget_project', models.TextField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('budget_currency', models.CharField(default='NGN', max_length=10)),
                ('tender_title', models.TextField(blank=True, null=True)),
                ('tender_value_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('tender_status', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(default=list)),
                ('parties', models.JSONField(default=list)),
                ('planning_data', models.JSONField(blank=True, default=dict, null=True)),
                ('tender_data', models.JSONField(blank=True, default=dict, null=True)),
                ('awards_data', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
