# Generated by Django 6.0.7 on 2026-07-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractingrelease',
            name='ocid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='contractingrelease',
            constraint=models.UniqueConstraint(fields=('ocid', 'release_id'), name='unique_ocid_release'),
        ),
    ]
